---
driver:
  name: terraform
  variable_files:
    - testing.tfvars

provisioner:
  name: terraform

platforms:
  - name: aws

transport:
  name: ssh
  path: ~/.ssh/your_ssh_key.pem

verifier:
  name: terraform

suites:
  - name: default
    verifier:
      systems:
        - name: {{cookiecutter.module_name}}
          backend: aws
          reporter:
            - cli
            - junit:test/integration/default/junit/junit.xml
      patterns:
        - test/integration/default/controls/*_spec.rb
