repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.76.0
  hooks:
  - id: terraform_validate
  - id: terraform_fmt
  - id: terraform_checkov
  - id: infracost_breakdown
  - id: terraform_docs
  - id: terraform_tflint
  - id: terraform_tfsec
  - id: terrascan
    args:
      - --args=--non-recursive
